### ISSUE TITLE
Simplify lists of enriched terms

### ISSUE THREAD

**Issue by tmmurali** [Murali-group/SARS-CoV-2-network-analysis#11]
As we expected, the enrichment analysis yields many highly similar statistically significant GO terms and KEGG and Reactome pathways. Moreover, the differences in enrichment across different sets of proteins (e.g., predictions from GeneMania+, predictions from SVM, PPI predictions) are hard to discern with such long lists. 

We need to implement a method that simplifies these lists across different protein sets. 

For an individual protein set (e.g., predictions from GeneMania+), we can 

1. build a graph where each node is a term or pathway and an edge connected two nodes with a weight equal to how similar the annotations are between the two nodes (after intersection with the protein set). We can measure similarity using the Jaccard index.

1. delete all edges below some weight (say, 0.75).

1. Pick a representative node from each cluster, say, the one with the smallest p-value.

This approach works for individual protein sets but the risk is that results become incomparable when applied independently to different protein sets. For example, for the cilium-related GO terms, we may pick "cilium assembly" for predictions from GeneMania+ but "focal adhesion assembly" for predictions from SVM. So we need some method that can pick "consistent" terms across protein sets. 

One idea is to build this graph across all protein sets and use the same idea as above. 

Another idea is to apply some sort of set cover algorithm. 
    - Consider all enriched terms/pathways across all protein sets.
    - A term/pathway contains the union of the proteins annotated to it in all the protein sets.
    - If we pick this term/pathway in the output, it covers all the proteins it contains.
    - The universe of proteins here is union of proteins across all terms/pathways (only considering the proteins in the protein sets)
    - Our goal is to pick a small set of terms/pathways so that they together cover the universe of proteins.
    - Ideally, we should take enrichment p-values into account. I suggest we give a weight to each term/pathway equal to the product of its p-value across all protein sets.

The greedy algorithm for weighted set cover iteratively picks terms/pathways till the entire universe is covered. In a iteration, it picks the term/pathway the maximises the weight of the term/pathway divided by the number of as-yet-uncovered proteins that are covered by the pathway.

**Comment by mcrovella** [comment]
Hi,

Do you know this paper: https://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1000443.   It tests many ways of comparing sets of GO annotations and in a nutshell recommends the Resnik score is the best performing way of measuring similarity of two annotation sets in GO.   Resnik score is defined in https://arxiv.org/abs/1105.5444.    (The key point here is that GO annotations are highly correlated because they are taken from a DAG and any two annotation sets consist of many overlapping terms high in the hierarchy).

This may be overkill for this purpose but I’d be happy to dig up my old code for this and see if it can be adapted to this task.

Mark

**Comment by tmmurali** [comment]
@n-tasnina we can close this issue, can't we? You can add a pointer to the function in the code that addresses this issue.

**Comment by n-tasnina** [comment]
We can close this issue. Here is the pointer to the function simplifying enriched terms.
https://github.com/Murali-group/SARS-CoV-2-network-analysis/blob/fd9b06d92dbe62676716a75b3350bb108f5b1564/src/Enrichment/fss_enrichment.py#L501
