### ISSUE TITLE
Repeat cross-validation multiple times

### ISSUE THREAD

**Issue by tmmurali** [Murali-group/SARS-CoV-2-network-analysis#3]
Add a parameter that will allow us to sample negatives multiple times. Compute box-plots of each algorithm across multiple sets of negative samples.

**Comment by jlaw9** [comment]
I added this functionality with the `--sample-neg-examples-factor` option to the FastSinkSource repo on the `no-ontology` branch. 

See these two commits:
https://github.com/jlaw9/FastSinkSource/commit/6e26a1fdb2c9b6847094b4d107f0a3277a9cc4b5
https://github.com/jlaw9/FastSinkSource/commit/a6f7c5f823c127df1c1c9f84fe75be702a85965c
