### ISSUE TITLE
Implement graph diffusion algorithm with parameter lambda

### ISSUE THREAD

**Issue by tmmurali** [Murali-group/SARS-CoV-2-network-analysis#4]
This approach has no negative examples but is like GeneMania otherwise. If 

1.  $W$ is the weighted adjacency matrix for an undirected graph $G$, 
1. f is a 0-1 vector over the nodes in $G$ with $f_i = 1$ if $i$ is a positive example and $f_i = 0$ otherwise, and
1. $\lambda > 0$ is a parameter,

compute a vector y that minimises,

$\sum_i (y_i - f_i)^2 + \lambda \sum_{i,j} W_{ij} (y_i - y_j)^2

The solution is $y = (I + \lambda (D - W))^{-1}f$, where $D$ is a diagonal matrix of weighted node degrees.

I suggest we invert the matrix explicitly.

**Comment by tmmurali** [comment]
Looks like jlaw9/fastsinksource already has this implemented as GeneManiaPlus: https://github.com/jlaw9/FastSinkSource/blob/master/src/algorithms/genemania_runner.py#L99 Only need to add the lambda parameter.

**Comment by jlaw9** [comment]
I added the `lambda` parameter as `alpha` since `lambda` is a keyword in Python, and added the algorithm `genemaniaplus` to the default config file.

https://github.com/jlaw9/FastSinkSource/commit/d47099063bfd6dc8abe2d1f24e33077960caae27
